# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
#stages:
#- test
#sast:
#  stage: test
#include:
#- template: Security/SAST.gitlab-ci.yml
image: debian:latest

variables:
    USER: root
    SERVER_IP: 78.47.35.181

before_script:
  - apt-get update
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stage_deploy:
  artifacts:
    paths:
      - build/
  script:
    #- ssh-add <(echo "$DEPLOY_KEY")
    - mkdir public
    - touch public/index.html
    - echo "<h1>New deployment<h1>" >> public/index.html
    - echo "$DEPLOY_KEY" | tr -d '\r' | ssh-add -
    - ssh -p22 $USER@$SERVER_IP "mkdir htdocs/wp-content/themes/_tmp"
    - scp -P22 -r build/* $USER@$SERVER_IP:htdocs/wp-content/themes/_tmp
    - ssh -p22 $USER@$SERVER_IP "mv htdocs/wp-content/themes/live htdocs/wp-content/themes/_old && mv htdocs/wp-content/themes/_tmp htdocs/wp-content/themes/live"
    - ssh -p22 $USER@$SERVER_IP "rm -rf htdocs/wp-content/themes/_old"
